### ISSUE TITLE
ATM9 모드팩 FTB Quest 번역시 오류

### ISSUE THREAD

**Issue by NyaHan16** [peunsu/mc-questing-mod-localizer#12]
https://mc-questing-mod-localizer.streamlit.app/

언어 파일 체크 에서
Yes 를 눌러 Json 파일만 번역할시에는 오류가 뜨지 않습니다.
대신 FTB Quest 의 챕터 목록 만 번역되고 Quest 내용은 번역되지 않습니다.

언어 파일 체크에서
No를 눌러 Chapters 폴더에 있는 snbt를 47개의 snbt를 번역하여
적용할 경우

![1](https://github.com/peunsu/mc-questing-mod-localizer/assets/153910972/081d5985-9cc6-4b33-b165-826e0d21b2ab)
![2](https://github.com/peunsu/mc-questing-mod-localizer/assets/153910972/b2376c1f-cfbd-4bdd-bdf2-d35721a17951)
이런식으로 오류가 납니다.

![3](https://github.com/peunsu/mc-questing-mod-localizer/assets/153910972/ebc809b7-3a4a-4c1b-a28d-4606def5f1bb)
이렇게 몇몇개는 오류가 안나고 정상적으로 나오는 경우도 있습니다.

번역했던 snbt 와 json 파일도 같이 올려봅니다.
[ATM9로컬라이징 번역 오류.zip](https://github.com/peunsu/mc-questing-mod-localizer/files/14327284/ATM9.zip)

**Comment by peunsu** [comment]
## 원인
작성하신 내용과 첨부파일을 확인해본 결과 제가 파악한 원인은 다음과 같습니다.
* 스크린샷에 `atm9.quest.welcome.desc.welcome1`와 같이 나타나는 키값들이 올려주신 JSON 파일에서 확인되지 않습니다.
* JSON에 확인되지 않는 키값은 **이 프로그램에서 생성한 키값이 아니며, 원래 모드팩에 포함된 JSON 파일에 등록되어 있던 키값입니다.**
* 원래 모드팩 퀘스트의 일부가 이미 [`en_us.json`](https://github.com/AllTheMods/ATM-9/blob/4ce28e0114269e55cc60eb6c6858f3518feba7b2/kubejs/assets/kubejs/lang/en_us.json)에 번역이 되어 있었고, 프로그램을 이용해 생성된 json 파일로 기존 json 파일을 덮어씌우면서 원래 있던 텍스트가 증발해버리는 현상이 나타난 것입니다.

아직 제 프로그램은 일부만 번역이 진행된 퀘스트, 그러니까 기존에 JSON 파일이 퀘스트의 일부를 번역한 내용만 남고 있을 경우에 대해서는 지원하지 않습니다. 따라서 지금 하실 수 있는 해결 방법은 다음과 같습니다.

## 해결 방법
1. 기존에 존재하는 json 파일을 다른 곳에 백업합니다.
2. 원래 하시던 대로 프로그램을 돌리시고, snbt 파일이랑 json 파일을 덮어씌웁니다.
3. [JSON Merger](https://paji-toolset.net/json-merger)에서 백업한 json 파일과 원래 json 파일을 합칩니다.
  * 한 칸에는 백업해둔 json 파일을, 다른 칸에는 프로그램 결과로 얻은 json 파일을 복사 붙여넣기로 넣으시고 오른쪽에서 Download 버튼을 누르시면 됩니다.

## 조치 사항
기존에 일부 번역된 JSON 파일이 존재하는 경우 그 파일을 업로드할 수 있도록 프로그램을 업데이트하겠습니다. 현재 군 복무 중인 관계로 시간은 좀 걸릴 것 같습니다 :)

감사합니다.

**Comment by NyaHan16** [comment]
군 복무중인데도 불구하고 이렇게 빨리 해결책을 알려주셔서 감사합니다.

제가 헷갈리는 것만 조금 더 물어보고 싶습니다.
해결책에 json 파일을 합치라고 하셧는데

1. 원본 en_us.json 과 프로그램을 돌린 en_us.json을 합치는 것인지

2. 원본 en_us.json 과 프로그램을 돌린 en_us.json을 한번 복사해둔 다른 원본 en_us.json에 덮어씌우고 
    원본과 덮어씌운것을 합치는것인지 헷갈려 한번 더 질문을 드립니다.
