### ISSUE TITLE
웹사이트 먹통

### ISSUE THREAD

**Issue by wnsgml0814** [peunsu/mc-questing-mod-localizer#32]
![image](https://github.com/user-attachments/assets/c6234035-f472-4154-819b-08c50ac154de)

**Comment by peunsu** [comment]
먼저 불편을 끼쳐드려 죄송합니다.
방금 사이트가 다운되었다는 사실을 인지하였고, 웹 서비스를 재부팅하여 현재는 정상적으로 접속하실 수 있습니다.
문제 상황을 알려주셔서 빠르게 조치할 수 있었습니다. 감사합니다.
앞으로도 다른 문제가 발생할 경우 이번과 같이 깃헙 이슈 페이지로 제보해주시면 감사드리겠습니다.
좋은 하루 되세요.
