### ISSUE TITLE
Error "issubclass() arg 1 must be a class"

### ISSUE THREAD

**Issue by NeauChar** [peunsu/mc-questing-mod-localizer#39]
**An error occurred while translating quests: issubclass() arg 1 must be a class**

Version used: FTB Quests 1.21+ Localizer (Beta)

Tried in 3 different browsers, the error is the same. Translation en_us -> ru_ru.

**Comment by peunsu** [comment]
> **An error occurred while translating quests: issubclass() arg 1 must be a class**
> 
> Version used: FTB Quests 1.21+ Localizer (Beta)
> 
> Tried in 3 different browsers, the error is the same. Translation en_us -> ru_ru.

Sorry for inconvenience.

For further investigation, please attach all of your quest files here :)

**Comment by NeauChar** [comment]
[Uploading chapters.zip…]()

**Comment by peunsu** [comment]
> Uploading chapters.zip…

I can't see your files.

**Comment by NeauChar** [comment]
I think it's loaded

**Comment by peunsu** [comment]
@NeauChar 

I think the problem is that you are using the localizer for MC 1.21+. Because your quest files have no language files, you should use the localizer for lower versions.

**Comment by peunsu** [comment]
> @NeauChar
> 
> I think the problem is that you are using the localizer for MC 1.21+. Because your quest files have no language files, you should use the localizer for lower versions.

And these were successfully translated into Russian using FTB Quests Localizer for under MC 1.21 version.

![image](https://github.com/user-attachments/assets/132df933-7a49-4ca0-80a6-1aceb898f2f4)

**Comment by NeauChar** [comment]
Indeed, tried translating with the old version, everything works. I apologize for distracting you 😅
